package archives.archives;

/**
 * Exception to throw when an error occurs during the creation of an occurrence
 * 
 * @author Alan BENIER
 */
public class OccurrenceException extends Exception{
	private static final long serialVersionUID = 5876404852210142928L;		// auto-generated by Eclipse
	private String exception;												// reason for the exception

	/**
	 * Default Constructor
	 * 
	 * @deprecated
	 */
	public OccurrenceException() {
		super();
		this.exception = "Unknown";
	}

	/**
	 * Create an exception
	 * 
	 * @param exp reason for the exception
	 */
	public OccurrenceException(String exp) {
		super(exp);
		this.exception = exp;
	}

	/**
	 * Getter
	 * 
	 * @return the reason for the exception
	 */
	public String getException() {
		return this.exception;
	}

	/**
	 * Print the reason for the exception on stderr
	 */
	public void printStackTrace() {
		System.err.println(exception);
	}
}